develop
Signed-off-by: tomas-zigardi <tomas.zigardi@accenture.com>

diff --git a/platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml b/platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml
--- a/platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml
+++ b/platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml
@@ -29,20 +29,60 @@ spec:
 
               chmod u+x kubectl && mv kubectl /bin/kubectl;
 
-              KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
-              KUBE_CERT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt);
 
-              echo ${KUBE_TOKEN}
-
-              echo aaaa;
-
-              echo ${KUBE_CERT};
-
-              kubectl version;
+              validateVaultResponse () {
+               if [ ${1} != 200 -a ${1} != 204 ]; then
+                echo "ERROR: Unable to retrieve. Http status: ${1}"
+                exit 1
+                fi
+               }
               
-              VAULT_TOKEN="$(curl --request POST --data '{"jwt": "'"$KUBE_TOKEN"'", "role": "{{ $.Values.account.admin_role }}"}' -s -k {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.admin_auth_path }}/login | jq -r '.auth.client_token')";
+              export KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
+              export KUBE_CERT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt);
               
-              echo bbb;
+              export VAULT_SA_NAME=$(kubectl get sa {{ $.Values.account.service }} -n {{ $.Values.metadata.namespace }} -o jsonpath="{.secrets[*]['name']}")
+              
+              export SA_CA_CRT=$(kubectl get secret $VAULT_SA_NAME -n {{ $.Values.metadata.namespace }} -o jsonpath="{.data['ca\.crt']}" | base64 -d; echo)
+              
+              
+              VAULT_TOKEN="$(curl --request POST --data '{"jwt": "'"$KUBE_TOKEN"'", "role": "rw"}' -s -k {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.admin_auth_path }}/login | jq -r '.auth.client_token')";
+              
+              SA_CA_CRT_ONELINE=$(kubectl get secret $VAULT_SA_NAME -n {{ $.Values.metadata.namespace }} -o jsonpath="{.data['ca\.crt']}" | base64 -d | awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}')
+              
+              
+              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data '{"type": "kubernetes"}' {{ $.Values.vault.address }}/v1/sys/auth/{{ $.Values.vault.auth_path }})
+              
+              validateVaultResponse ${response_status};
+              
+              # Check 
+              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.auth_path }}/config)
+
+              validateVaultResponse ${response_status};
+              
+              
+              response_status=$(curl  -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data '{"kubernetes_host": "{{ $.Values.network.kubernetes_url }}", "kubernetes_ca_cert": "'"$SA_CA_CRT_ONELINE"'", "token_reviewer_jwt": "'"$SA_JWT_TOKEN"'"}' -s -k {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.auth_path }}/config)
+              
+              validateVaultResponse ${response_status};
+              
+              
+              
+              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" --request PUT --data '{"policy": "{{ $.Values.vault.policy_content }}"}' {{ $.Values.vault.address }}/v1/sys/policy/{{ $.Values.vault.policy }})
+              
+              validateVaultResponse ${response_status};
+              
+              # Check policy
+              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" {{ $.Values.vault.address }}/v1/sys/policy/{{ $.Values.vault.policy }})
+
+              validateVaultResponse ${response_status};
+            
+              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data '{"bound_service_account_names": "{{ $.Values.account.service }}","bound_service_account_namespaces": "{{ $.Values.metadata.namespace }}","policies": ["{{ $.Values.vault.policy }}"], "ttl": 180}' {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.auth_path }}/role/{{ $.Values.account.role }})
+              
+              validateVaultResponse ${response_status};
+
+              # Check role
+              response_status=$(curl -s -o /dev/null -w "%{http_code}" --header "X-Vault-Token: $VAULT_TOKEN" {{ $.Values.vault.address }}/v1/auth/{{ $.Values.vault.auth_path }}/role/{{ $.Values.account.role }})
+
+              validateVaultResponse ${response_status};
 
               echo ${VAULT_TOKEN};
               sleep 10000;
